# Generated by Django 5.0.7 on 2025-05-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('account_id', models.CharField(max_length=10, unique=True, verbose_name='アカウントID')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='スーパーユーザー')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
